### ISSUE TITLE
How to get VGG-SS & Flicker 144k

### ISSUE THREAD

**Issue by Sunjuhyeong** [stoneMo/SLAVC#1]
Hello !
First of all, thank you for your nice work. It would be helpful for future research of VSL :)

I'd like to ask you the methods: how to get the VGG-SS.
Is it right, from vggss.csv, get frame of the timestamp (t) & get the .wav file of 10 seconds (t ~ t+10 s) ?
Also, for the flickr, I can't find even any csv files.

Would you mind if I ask you to share, how can I get the VGG-SS & Flickr with code or command, or even website ?

**Comment by stoneMo** [comment]
Hi! Thanks for your interest in our work. These two datasets can be originally downloaded from [VGG-SS](https://www.robots.ox.ac.uk/~vgg/data/vggsound/) and [Flickr](http://soundnet.csail.mit.edu/). 
Your understanding of vggss.csv is correct. For Flickr, we provide 144k video ids in [flickr_144k.txt](https://github.com/stoneMo/SLAVC/blob/main/metadata/flickr_144k.txt) for training.
