### ISSUE TITLE
Help with reproducing VGGSS-EXTEND

### ISSUE THREAD

**Issue by cyh-0** [stoneMo/SLAVC#2]
Hi Mo,

Thanks for sharing the code and dataset. I currently working on reproducing the results for the "Extended VGG-Sound Source" dataset to verify the video data pre-processing. I failed to achieve the results listed on the README page and what I got is about 40% lower. For example:
==================== AV+OGL ====================
 - AP-all@50: 0.2351479097289724
 - AUC-all@50: 0.3747188832880961
 - F1-all@50: 27.4 29.7 31.7 32.7 32.9 32.1 29.3 24.1 18.5 10.5 0.1
 - Precision-all@50: 0.1590732842186894
 
What I have done is simply download the dataset from "https://drive.google.com/file/d/1dcaSyJ8xyfCPKmESDLyKucglm-1ROEOt/view" and use the following script to run the testing file:

```
python test.py --test_data_path "./VGGSound-test-plus-silent/" --model_dir ./ckpt/checkpoints --experiment_name vggss144k_slavc --testset vggss_plus_silent --alpha 0.9
```
I am not sure which parts went wrong on my side, hopefully, you could help me with that.
Looking forward to hearing from you

YH

**Comment by stoneMo** [comment]
Hi! Thanks for your interest in our work. You need to use `--relative_prediction`, and please note that the `default_conf_thr` should be 0.5 in the Evaluator. Then you will get the following results. Also, Precision/LocAcc is only used for visible/sounding objects. 

==================== AV+OGL ====================
 - AP-all@50: 0.34458781073824324
 - AUC-all@50: 0.4010663047692904
 - F1-all@50: 33.2 35.5 38.1 40.3 41.5 41.2 39.1 33.9 27.1 16.0 0.1
 - Precision-visible@50: 0.39802248933695233

**Comment by cyh-0** [comment]
Hi Mo, 

Thanks for the update, I have another issue with the audio pre-processing. Wherein the paper, the spectrogram (line 37 in datasets.py) is defined to have 257x300. But, based on my experiment, I always got 257x554 which is a bit confusing...

And after updating my script to 
```
python test.py \
    --experiment_name vggss144k_movsl \
    --testset 'vggss_plus_silent' \
    --alpha 0.9 \
    --relative_prediction
```
and default_conf_thr=0.5, my results are:
- AP-all@50: **0.3192457951964751**
- AUC-all@50: 0.4010856921287321
- F1-all@50: 33.2 35.5 37.7 39.2 **39.8** 39.5 37.1 31.6 24.9 14.7 0.1
- Precision-visible@50: 0.39860411012020164
Which is still slightly lower than your results.

Cheers,
YH
